### ISSUE TITLE
Multisig - only one transaction to sign when sending couple of them

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-mobile-wallet#10]
Steps:

1. Create 2 of 2 multisig where one cosigner is desktop and second mobile.
2. Init couple transactions from desktop multisig. For example 4.
3. On mobile is presented only one transaction to sign instead 4 (I'm switched to multisig)
4. I imported mobile cosigner on desktop and I can see 4 transactions to sign.
5. After I sign only visible transaction on mobile there is no others to sign. On desktop still 3 Partial tranactions left.

**Comment by OlegMakarenko** [comment]
@cryptoBeliever I can't reproduce this bug. Can you please tell me the version did you used?

**Comment by cryptoBeliever** [comment]
@OlegMakarenko I'm not able to reproduce on latest version of app. Looks like fixed already :+1:
