### ISSUE TITLE
Making encrypted messages with iOS app, can't read on desktop app or mobile app

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#103]
**Steps to reproduce**
make an encrypted message, later try to read it. 

**Current behavior**
the message is blank.  not sure why. 

**Expected behavior**
to see the encrypted 
 
**Affected Version**
latest iOS app

**Comment by Peersyst** [comment]
Is that happening with all transactions? Or only unconfirmed? We have noticed that this is happening only for unconfirmed transactions.

**Comment by cryptoBeliever** [comment]
@NikolaiB could you check?

**Comment by NikolaiB** [comment]
@cryptoBeliever @jabo38 fixed.

**Comment by cryptoBeliever** [comment]
Ok. Marked as fixed.
