### ISSUE TITLE
Scanning QR from the desktop app while using mobile phone don't work correctly

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#105]
**Steps to reproduce**
To be clear, using the QR code shortcut on the main dashboard works fine. Using the QR shortcut from the send menu next to the recipient field does not work. 

**Current behavior**
doesn't work. gets an error

**Expected behavior**
to have the address autofilled. 
 
**Affected Version**
Latest version of iOS and Desktop

**Comment by Peersyst** [comment]
We are unable to reproduce it. The address scanner only works for AddressQR and ContactQR.

**Comment by jabo38** [comment]
It should work for invoice QRs too. If the desktop wallet is making 2 different ways for a person to send their user information, people will send 2 kinds.

**Comment by cryptoBeliever** [comment]
App is scanning now Invoice QRs
