### ISSUE TITLE
can add the same name and same address to address book many times, even on accident. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#106]
**Steps to reproduce**
scan a QR
add it to the address book
screen goes back to the screen where there is the add button
add it again
add it again
now there are many versions of the same name and address. 

Why would a user click the button more than once? because it is there, maybe they thought the first time is a bug or it didn't save, or they hit the wrong button so they try again. 

**Current behavior**
the "add" button should not be clickable if an address is already added. If anything it should be an "edit" button.  

**Expected behavior**
there should not be multiple entries for the same name and address. 

If there is an entry with that name, then an error says that name already exists, if it is an address that is duplicated then there should be an error that address is already added, if both like this, then an error of one, both, or the other. 

**Affected Version**
latest version of iOS

**Comment by NikolaiB** [comment]
@jabo38 @cryptoBeliever fixed.

**Comment by cryptoBeliever** [comment]
ok.
