### ISSUE TITLE
Update Delete all accounts Rus translation

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-mobile-wallet#117]
There are still a couple of issues with Rus translation:

1. The last word should be 'Удалить все аккаунты'
![image](https://user-images.githubusercontent.com/11311924/106910314-4d1e0600-672b-11eb-9114-f79e5b279663.png)

2. The confirmation translation next to the checkbox should look like this: `Я сохранил все аккаунты связанные с этим профилем.`
![image](https://user-images.githubusercontent.com/11311924/106911690-9f135b80-672c-11eb-971e-1595b4884e75.png)

**Comment by cryptoBeliever** [comment]
Fixed.
