### ISSUE TITLE
Unable to import an account for both iOS and Android [BUG]

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-mobile-wallet#119]
**Steps to reproduce**

1. Install the latest version of mobile app
2. Launch the app
3. Accept the Terms
4. Tap on "Import It"
5. Scan QR code for mnemonics of an existing account or enter mnemonics manually
6. Notice the actual address does not correspond to an imported one

**Current behavior**
New account is created instead of importing of an existing one with QR code or manually typying its mnemonics

**Expected behavior**
The selected preexisting account gets imported to the mobile app
 
**Affected Version**
4 (11)

**Platform details**
both iOS and Android
 
[Video](https://share.getcloudapp.com/Qwu9G72K)

**Comment by cryptoBeliever** [comment]
Did you imported mnemonic from old paper wallet? If yes, then this is expected for testnet (derivation path changed).

**Comment by cryptoBeliever** [comment]
@Eugenity please confirm :)

**Comment by Eugenity** [comment]
@cryptoBeliever Confirm. Now it is not reproducible.
