### ISSUE TITLE
Big account amount goes to a new line

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-mobile-wallet#12]
![image](https://user-images.githubusercontent.com/17684281/99994762-babbc680-2db9-11eb-8574-417f2a4d0098.png)

For Android it's same two digits don't fit for amount 41743186.753352

**Comment by cryptoBeliever** [comment]
@OlegMakarenko on accounts view it's fixed. There are still some not visible digits on dashbord:

![Screenshot_20201126-211906_Symbol Beta](https://user-images.githubusercontent.com/17684281/100389295-51dc8480-302d-11eb-819a-7111158dc5e6.jpg)

But I think that no one with such amount will use mobile wallet (on mainnet). Please check if we can this easly improve.

**Comment by OlegMakarenko** [comment]
@cryptoBeliever thanks, I will think about how to improve it
