### ISSUE TITLE
There is no way to add a node

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#121]
Most diehard enthusiasts run their own node and want their wallet to connect to it. 

**Describe the solution you'd like**
There should be a section for adding a custom node. So the node selection area should have "Testnet/Mainnet/Custom" and in Custom, a person can connect to their own node by manually entering the node information. 

**Describe alternatives you've considered**
Instead of a white list of NGL approved nodes, the app pulls from a list of all the most commonly known nodes on the network and lists those in a searchable way.

**Comment by cryptoBeliever** [comment]
Fixed.
