### ISSUE TITLE
Activation in progress status doesn't change to Active 

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-mobile-wallet#123]
WTR:

1. Activate Harvesting
2. Open Desktop and mobile wallet on harvesting page

Result: You can see that on Desktop wallet harvesting status is Active but mobile is Activation in progress
![image](https://user-images.githubusercontent.com/11311924/107241623-5d98ee00-6a55-11eb-83f3-9235a817bd3f.png)

**Comment by cryptoBeliever** [comment]
Closing and leaving https://github.com/nemgrouplimited/symbol-mobile-wallet/issues/134
