### ISSUE TITLE
[iOS] Back arrow and Menu icon are very difficult to click

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-mobile-wallet#13]
WTR:
1. Add an account
2. Click Wallet icon
3. Try to click back arrow and menu item icons
Result: For iPhone versions >= X Back arrow and Menu item icons are very difficult to click.

![image](https://user-images.githubusercontent.com/17684281/99994842-dfb03980-2db9-11eb-9032-630b11009949.png)

**Comment by NikolaiB** [comment]
@cryptoBeliever it's fixed for iOS.

**Comment by cryptoBeliever** [comment]
It's OK
