### ISSUE TITLE
[Bug] Cannot encrypt message for a recipient account w/o transactions

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-mobile-wallet#136]
A user is unable to initiate a transaction with selected Encrypted checkbox. There was [a similar issue](https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/753) for a desktop wallet which was fixed before.

**Steps to reproduce:**
1. Create a profile
2. Create seed account
3. Claim tokens from faucet link for the first account
4. Use Send function for a first account
5. Specify To field with an address of the seed account
6. Type acything in the Message field
7. Tap Encrypted checkbox
8. Tap Send button
9. Tap Confirm

Actual result: The transaction is not initiated, confirmation page is blank
Expected result: A user is able to initiate transaction with encrypted message for a new recipient account

[Video](https://user-images.githubusercontent.com/19706018/108755580-2136b900-7550-11eb-8bd3-a7d54d222af8.mp4)

**Comment by jabo38** [comment]
I think that there is no way to do this because of the fact the network doesn't know the other user's public key, but it would be really good to show a proper error message here as they try to encrypt or what not to prevent the other problems.

**Comment by cryptoBeliever** [comment]
Yes. To encrypt you need to have sender private key and recipient public key. The second one is not accessible for not known accounts. However, message is not clear.
