### ISSUE TITLE
Add delimiter for transaction fee

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-mobile-wallet#138]
![image](https://user-images.githubusercontent.com/11311924/109783945-badb2600-7c34-11eb-981d-b8654bf08461.png)

**Comment by NikolaiB** [comment]
@OlegMakarenko @Peersyst I still can reproduce it for iOS 
![image](https://user-images.githubusercontent.com/11311924/110466905-8cf85480-8100-11eb-8834-f71812b9f8cb.png)

**Comment by jabo38** [comment]
I had this same bug on iOS

**Comment by NikolaiB** [comment]
fixed v4(30)
