### ISSUE TITLE
[iOS] App crashes when transaction detail item was clicked

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-mobile-wallet#14]
WTR:
1. Create my own mosaic
2. Initiate transaction with own mosaic
3. Go to History page and click on transaction detail item
Result: App crashes

![image](https://user-images.githubusercontent.com/17684281/99994918-fa82ae00-2db9-11eb-9a5a-736428f09d98.png)

**Comment by NikolaiB** [comment]
Fixed in version 3.0.8200
