### ISSUE TITLE
Move toast messages below the Notch

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-mobile-wallet#143]
If the app is used on iPones with Notch display than toast messages are half visible, as a solution they can be moved lower like on a second pic. 
![image](https://user-images.githubusercontent.com/11311924/110756410-59d6d200-8274-11eb-8555-13ad63e13539.png)

**Comment by NikolaiB** [comment]
@OlegMakarenko @Peersyst fixed.

**Comment by cryptoBeliever** [comment]
Fixed, merged, released.
