### ISSUE TITLE
Not able to send all coins from mobile wallet

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-mobile-wallet#152]
Main net

Steps:

1. Create account with balance 100.9824 XYM
2. Go to send form and try send all of it (minus fee)

Result: App allow me send only 99.78 but fee for this transfer is 0.0176. I'm not able send all of it from wallet.

**Comment by surekabpm** [comment]
I tested this issue in testnet ,Android mobile and is fixed , this PR can be merged

**Comment by surekabpm** [comment]
Hi, I tried testing this issue, added 100 to the wallet , the recommended fee is 0.0176 or no fees, i selected 99 to send, but it says not enough funds ... so i think still not able to send all the coins . so retest failed , please have a look

**Comment by cryptoBeliever** [comment]
Tested. I was able to send all coins.
Tested, merged and released.
