### ISSUE TITLE
Transaction list -> Tranasaction detail -> Wrong explorer link

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-mobile-wallet#153]
Steps:

1. Go to transaction list
2. Open transaction detail
3. Click explorer link

App redirects you to testnet explorer on main net profile

**Comment by jabo38** [comment]
I know it is a day later, but I want to report a similar  but slightly different issue. 

For me when I click on the explorer link, it doesn't take me anywhere.

**Comment by NikolaiB** [comment]
@cryptoBeliever @jabo38 fixed.

**Comment by cryptoBeliever** [comment]
I closed it but opened https://github.com/nemgrouplimited/symbol-mobile-wallet/issues/214
