### ISSUE TITLE
maybe say "there is nothing here to to display" on the history screen when no history

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#158]
**Is your feature request related to a problem? Please describe.**
no problem, just an idea for improvement

**Describe the solution you'd like**
right now when I have an account with 0 tx history and I go to the history page, it is white space. 

**Describe alternatives you've considered**
for instance on the block explorer, it will say "this account does not have a public key" 

![image](https://user-images.githubusercontent.com/10395907/111559800-8f455900-8767-11eb-8566-6d27dc27be9e.png)

Maybe don't say that but instead maybe say "this account does not have a transaction history" in grey letters instead of the big white space. I see now. 

![image](https://user-images.githubusercontent.com/10395907/111559865-b1d77200-8767-11eb-97d3-b28f2a8c493a.png)

**Additional context**
maybe if a person only has incoming and you filter for outgoing, you could say "this account does not have any out going transactions" in grey letters

**Comment by NikolaiB** [comment]
@OlegMakarenko @Peersyst @jabo38 fixed.

**Comment by cryptoBeliever** [comment]
Tested, merged, released.
