### ISSUE TITLE
Can't sign multisig txs at all

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#159]
**Steps to reproduce**
Create a set of accounts and signers on desktop, use same set of accounts and signers on phone. 

**Current behavior**
Can see all confirmed txs but can't see any unconfirmed txs waiting to be signed. 

**Expected behavior**
Ideally on the Home panel a notification that I have txs to sign so I don't have to dig for them. But at least in the history panel I can click on the pending tx and sign. 
 
**Affected Version**
iOS iPhone 11  (I would list a version number but there is no version number, which is really important) 

**Screenshots**
Ideally something like this could be nice. but at least be able to sign in the history page. 

[Optional]
![image](https://user-images.githubusercontent.com/10395907/111710619-66cd6580-8820-11eb-8ae3-6b62e3c8458c.png)

**Comment by Peersyst** [comment]
@jabo38 Have you tried switching the account selector on history menu? It should appear under the multisig account

**Comment by OlegMakarenko** [comment]
> Have you tried switching the account selector on history menu? It should appear under the multisig account

Same with the Android version. Partial transactions are not visible on both tabs

**Comment by cryptoBeliever** [comment]
Now works for me (Android production app). Closing.
