### ISSUE TITLE
App freeze on PIN view

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-mobile-wallet#160]
Some of users reporting that app freeze on PIN screen:

![image](https://user-images.githubusercontent.com/17684281/111865004-aa30ec80-8964-11eb-994a-49a0fb8d750c.png)

**Comment by cryptoBeliever** [comment]
![Uploading image.png…]()

**Comment by cryptoBeliever** [comment]
![image](https://user-images.githubusercontent.com/17684281/111865019-bc128f80-8964-11eb-9852-0c2c4d046ec9.png)

**Comment by cryptoBeliever** [comment]
![image](https://user-images.githubusercontent.com/17684281/111865079-27f4f800-8965-11eb-8981-3fddb00e55d0.png)

**Comment by cryptoBeliever** [comment]
![Uploading image.png…]()

**Comment by cryptoBeliever** [comment]
![image](https://user-images.githubusercontent.com/17684281/111868025-f0437b80-8977-11eb-885d-0009dd9b9e13.png)

**Comment by cryptoBeliever** [comment]
![image](https://user-images.githubusercontent.com/17684281/111868178-b45ce600-8978-11eb-8713-60774231987b.png)

**Comment by Santiago26801** [comment]
I have this problem too

**Comment by Santiago26801** [comment]
https://github.com/nemgrouplimited/symbol-mobile-wallet/issues/160#issue-836761620

**Comment by Santiago26801** [comment]
Не понятно, как прикрепить сюда скриншот

**Comment by cryptoBeliever** [comment]
Same:
Samsung Galaxy 7 (2017)
Android 8.0.0

**Comment by Santiago26801** [comment]
Xiaomi Mi8
Miui 10 ver 8.8.9 beta

**Comment by cryptoBeliever** [comment]
![image](https://user-images.githubusercontent.com/17684281/112369567-9971d500-8cdc-11eb-8ebb-500f26065d44.png)

**Comment by mikunNEM** [comment]
Galaxy S7 edge SC-02H  /  AndroidTM 6.0

**Comment by cryptoBeliever** [comment]
Released.
