### ISSUE TITLE
Transaction listener doesn't work

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-mobile-wallet#164]

**Comment by surekabpm** [comment]
Hi Based on the below steps , i tried testing , but not able to see transaction in offline mode ,attached the screenshot
1. Open the mobile wallet
2. Go to History screen
3. Disconnect from the internet
4. After some time (red banner appears) connect back to the internet.
5. Do not leave the History screen. Announce any transaction from another device to the mobile wallet account address.
6. Transaction should appear in the mobile wallet automatically
![image](https://user-images.githubusercontent.com/49143210/114824094-03643280-9de2-11eb-9fdd-4172f42956e5.png)

**Comment by surekabpm** [comment]
This issue is fixed and tested and can be merged
