### ISSUE TITLE
Harvesting node list - allow put custom node

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-mobile-wallet#165]
Harvesting node list should allow put custom node.
Currently, it's not possible and not always /node/peers returns all nodes

**Comment by surekabpm** [comment]
Hi , I tried to enter an url in custom node , but there is no ok button/finish button to accept the node.hence the issue is still not fixed
![image](https://user-images.githubusercontent.com/49143210/113673442-a1674700-96d6-11eb-8f9f-1f3721e860c3.png)

**Comment by surekabpm** [comment]
issue resolved , this PR can be merged , but only one Observation after selecting the custom node, in settings page node still points to testnet , i think i need to raise a seperate defect
![image](https://user-images.githubusercontent.com/49143210/114139140-4a5aaf80-992c-11eb-9e8c-b0a49ca2bc6a.png)
![image](https://user-images.githubusercontent.com/49143210/114139448-b3dabe00-992c-11eb-8c11-1e684da620f2.png)

**Comment by cryptoBeliever** [comment]
@surekabpm it's because you provided testnet node.

Issue is tested, merged and released.
