### ISSUE TITLE
Delegated harvesting - wrong keys

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-mobile-wallet#169]
Is possible that public keys for linked and vrf are presented incorrectly on mobile wallet?
We received report about incosistency between desktop and mobile wallet:

Example 1:

![image](https://user-images.githubusercontent.com/17684281/112370140-52381400-8cdd-11eb-8e52-5eaa0324cbf9.png)
![image](https://user-images.githubusercontent.com/17684281/112370150-5401d780-8cdd-11eb-8179-4dacae02f6d8.png)

Example 2:

![image](https://user-images.githubusercontent.com/17684281/112370187-5e23d600-8cdd-11eb-8657-d726303c7c66.png)
![image](https://user-images.githubusercontent.com/17684281/112370170-5a904f00-8cdd-11eb-9d5c-5e015f2751bc.png)

**Comment by surekabpm** [comment]
This PR is tested and can be merged
