### ISSUE TITLE
Home screen. Notifications are not scrollable

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-mobile-wallet#17]

**Comment by cryptoBeliever** [comment]
@OlegMakarenko it's about notifications under Send/Receive buttons on dashboard?

**Comment by OlegMakarenko** [comment]
@cryptoBeliever yes it is

**Comment by cryptoBeliever** [comment]
@OlegMakarenko thanks. Checked. Now I'm able scroll notifications.
