### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by taki-jp** [nemgrouplimited/symbol-mobile-wallet#174]
At symbol-mobile-wallet/src/locales/translations/ja.json line 447 and 448,
the translations seem to be reversed.

It should be as follows.

447 |    "transferFrom": "受信",
448 |    "transferTo": "送信",

Please fix them.

**Comment by OlegMakarenko** [comment]
Thank you

**Comment by NikolaiB** [comment]
@OlegMakarenko still can reproduce it iOS v4.2(32)
![IMG_ED8FB3B71870-1](https://user-images.githubusercontent.com/11311924/113579538-4554e200-9646-11eb-9c59-f3b3d18a5b69.jpeg)

**Comment by cryptoBeliever** [comment]
Tested, merged, released.
