### ISSUE TITLE
Home screen. AccountBalanceWidget displays "0" balance while loading.

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-mobile-wallet#19]
Replace incorrect data with loading animation

**Comment by cryptoBeliever** [comment]
Fixed in latest revision (symbol-wallet-prod0.4-11-gc3068a7-c3068a7-201126-release.apk). I'm closing.

**Comment by cryptoBeliever** [comment]
Fixed in latest revision (symbol-wallet-prod0.4-11-gc3068a7-c3068a7-201126-release.apk). I'm closing.
