### ISSUE TITLE
[iOS vs Android] Invalid QR code from opt-in paper wallet

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-mobile-wallet#2]
WTR:
1. Go to your desktop account
2. Download paper wallet
3. Open mobile wallet and click Add Account button
4. Enter account name
5. Choose Create from private key in Account type dropdown list
6. Click Import by QR button and scan QR code from paper wallet
Result: Getting invalid QR code

![image](https://user-images.githubusercontent.com/17684281/100350287-efae6000-2fe9-11eb-896a-b2a9dc14a21f.png)

**Comment by userNikolai** [comment]
@Peersyst please find the updated description below
WTR:
1. Go to your desktop account
2. Download paper wallet
3. Open mobile wallet and click Add Account button
4. Enter account name
5. Choose Create from private key in Account type dropdown list
6. Click Import by QR button and scan QR code from paper wallet
Result: Getting invalid QR code

**Comment by cryptoBeliever** [comment]
There are two types of QR's you can import account:
- mnemonic QR - you can import it right after installing app
- private key QR - allow to add account on accounts view from private key.

Confirmed with @userNikolai that it works as designed.
