### ISSUE TITLE
Add QR type captions. Move QR logic to a separate reusable component

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-mobile-wallet#26]
![image](https://user-images.githubusercontent.com/33131259/100142900-2fb3fc80-2e9d-11eb-86ed-32194f738cce.png)

- [x] Create reusable component **QRImage**
- [x] Add support for type `address`
- [x] Add support for type `privateKey`
- [x] Add support for type `transaction`
- [ ] Add support for type `mnemonic`
- [x] Add the **secure view** for privateKey
- [x] Add the **create password** modal for privateKey
- [x] Move replace the qr logic from all screens with new component
- [ ] Add captions to the **QR scanner**

**Comment by cryptoBeliever** [comment]
@OlegMakarenko could you add more details what should be tested in this task?

**Comment by OlegMakarenko** [comment]
@cryptoBeliever QR images in the wallet's screens should be readable with another mobile and desktop wallets
