### ISSUE TITLE
Sidebar. Account selector item displays 'null' instead of index

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-mobile-wallet#28]
![image](https://user-images.githubusercontent.com/33131259/100159029-b7a60080-2eb5-11eb-8c70-abdfd1e428c3.png)

**Comment by Peersyst** [comment]
I think that this was from a breaking change of a version update. Check it and close it if you aren't unable to reproduce

**Comment by cryptoBeliever** [comment]
@OlegMakarenko 
I'm unable to reproduce.

![Screenshot_20201126-213415_Symbol Beta](https://user-images.githubusercontent.com/17684281/100390027-5f930980-302f-11eb-8f67-0f736b2cb714.jpg)

If you confirm that you can close.
