### ISSUE TITLE
[iOS vs Android] Compatibility with old mobile wallet versions doesn't work

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-mobile-wallet#3]
WTR:
1. Install the previous mobile wallet version. 
2. Opt-in account 
3. Update the wallet to latest one (For Android it installs as second app)
Result: there are no accounts

**Comment by OlegMakarenko** [comment]
@cryptoBeliever  iOS **and** Android?

**Comment by cryptoBeliever** [comment]
@OlegMakarenko sorry I missed your question somehow ...
This one was reported via Asana by @NikolaiB.

I think we need a way to test if opt-in app will update correctly. Can we do it somehow?

**Comment by cryptoBeliever** [comment]
@Peersyst how can we verify compability?

**Comment by NikolaiB** [comment]
@cryptoBeliever @Peersyst I suppose the only way is to run catapult-opt-in-toolkit that is pulling the data from nis1 and gerneating the symbol network using bootstrap but there is a bug that Fernando should fix first [#81](https://github.com/nemtech/symbol-bootstrap/issues/81).

**Comment by cryptoBeliever** [comment]
@NikolaiB Hmmm. I don't want to verify (at least not in issue) if opt-in data are correct. I want verify if after wallet update all will be ok.

@OlegMakarenko Yes, both IOS and Android. It would be nice to verify upgrade current production (opt-in only) app with new wallet and check if all works correctly.
- old profile should work without problems
- how many child accounts will be added if someone for example opted-in couple NIS1 accounts.

**Comment by Pow1404** [comment]
@cryptoBeliever @AdriaCarrera Do we still view as a P1 issue?

**Comment by cryptoBeliever** [comment]
@Pow1404 We need to test somehow update the current opt-in app using the store. It applies to Android and IOS.
@AdriaCarrera Did you tested this scenario? I mean hear if accounts will be created automatically based on opt-in data (checking if accounts have funds and adding automatically) and if there will be no other issues (like missing data) after update.

**Comment by NikolaiB** [comment]
fixed v4.1(31)
