### ISSUE TITLE
Harvesting screen. The harvesting status stuck on "Activation in progress"

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-mobile-wallet#34]
![image](https://user-images.githubusercontent.com/33131259/100296497-15f5e080-2f95-11eb-8e27-589f4ccfa408.png)

**Comment by Peersyst** [comment]
This could potentially happen for two reasons:
- The api rest node connected to is not updated. Still using previous version without the /unlocked entry-point.
- Not enough funds to start harvesting

Would be fine if you can test it and reproduce the error with the correct node and enough funds.

**Comment by cryptoBeliever** [comment]
@OlegMakarenko 
I think that it's because only dual nodes have `unlockedAccount` endpoint. Those available on list (beacon nodes) are not dual nodes.
