### ISSUE TITLE
[Android] Backup account is hanging on Enter Passcode window

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-mobile-wallet#38]
WTR:

1. Go to Settings page and click Backup
2. Enter Passcode

Result: Nothing happens, it is just hanging on Enter Passcode window

App version: 201126

![image](https://user-images.githubusercontent.com/11311924/100451492-b6591b80-30e1-11eb-92f6-f8fe16e003d1.png)

**Comment by cryptoBeliever** [comment]
Some for me. Something broke in the latest releases.

**Comment by cryptoBeliever** [comment]
It's fixed in latest version.
