### ISSUE TITLE
The message encrypted need to be decrypted in the transaction 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-mobile-wallet#39]
I had completed a transaction of sending XEM to an account, entered a message and checked encrypted, once the transaction is completed, I don't see the option to decrypt @AdriaCarrera 
![image](https://user-images.githubusercontent.com/49143210/100451753-f1f1e680-30dd-11eb-988b-c9f8c7636624.png)

**Comment by cryptoBeliever** [comment]
@surekabpm it's duplicate -> https://github.com/nemgrouplimited/symbol-mobile-wallet/issues/4
