### ISSUE TITLE
No option to decrypt message on sender side

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-mobile-wallet#4]
Steps:

I have two accounts A and B

1. I'm sending encrypted message from A to B
2. On B there is option to decrypt message on transaction details (OK)
3. On A there is no option to decrypt message on transaction details (BUG)

**Comment by NikolaiB** [comment]
@OlegMakarenko with the latest update in version 201126 you can see **Decrypt** button but when you click on it you don't see the message 
![image](https://user-images.githubusercontent.com/11311924/100343583-bede2300-3009-11eb-8683-411363aac00f.png)

**Comment by OlegMakarenko** [comment]
@NikolaiB what is the actual decrypted message payload (text) in this transaction?

**Comment by cryptoBeliever** [comment]
On Android (latest build) I have still issue from first comment. There is an option to decrypt on receiver (and it works) but there is no decrypt button on sender.

**Comment by cryptoBeliever** [comment]
Fixed.
