### ISSUE TITLE
Create Symbol QR scaner

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-mobile-wallet#48]

**Comment by cryptoBeliever** [comment]
@OlegMakarenko could you add more details what was changed in this task?

**Comment by OlegMakarenko** [comment]
Added QR scanner page which allows to scan majority of the Symbol QRs. Accessible from home page

**Comment by OlegMakarenko** [comment]
@cryptoBeliever Added QR scanner page which allows to scan majority of the Symbol QRs. Accessible from home page
