### ISSUE TITLE
[iOS][Android] [Harvesting] Shows different statuses on Harvesting page

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-mobile-wallet#53]
version: 4(3)

WTR:
1. Go to the web version and activate harvesting
2. Then **Stop Harvesting**
3. Open mobile app with the same account and go to Harvesting page

Result: on the web page the status changed to **Inactive** but on the mobile page it shows **Keys Linked** and Stop Harvesting button. (The page was refreshed and the app was restarted)

![image](https://user-images.githubusercontent.com/11311924/101782189-e8776e00-3b22-11eb-8e07-92ae4f0a72e0.png)
![image](https://user-images.githubusercontent.com/11311924/101782588-66d41000-3b23-11eb-90fe-89c883fde301.png)

**Comment by cryptoBeliever** [comment]
I was able to reproduce in mobile app itself. I stopped harvesting, transaction was confirmed and I had still "Keys linked". I had to restart app to make it refreshed.

**Comment by Peersyst** [comment]
Harvesting needs to be redone.

#77
