### ISSUE TITLE
+ sign is been taken as amount in the send transaction

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-mobile-wallet#58]
I'm validating the amount field as numerical field ,i entered as + sign in amount , it is not showing any error and the transaction is getting completed.
![image](https://user-images.githubusercontent.com/49143210/101905480-8c255480-3bdd-11eb-8408-4e3fcd62b06c.png)

**Comment by surekabpm** [comment]
![image](https://user-images.githubusercontent.com/49143210/101905618-bd9e2000-3bdd-11eb-9de0-dd90a6f0bdbd.png)

**Comment by cryptoBeliever** [comment]
Same issue when we put dot character. On next screen is presented NaN as transfered amount. As a result 0 is transfered.

**Comment by cryptoBeliever** [comment]
Not merged yet. Still I'm able reproduce by putting . (dot)

**Comment by cryptoBeliever** [comment]
Fixed.
