### ISSUE TITLE
Remove and Hide buttons are displayed alternatively

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-mobile-wallet#63]
I have logged in Android mobile wallet, created an account , added another account thru a private key .now check the both accounts , remove button and hide button are there . hide needs be to remove
![image](https://user-images.githubusercontent.com/49143210/102083007-e8d07b80-3e38-11eb-8c3c-581a1fd53277.png)
![image](https://user-images.githubusercontent.com/49143210/102083073-fede3c00-3e38-11eb-82af-a71d0db560c1.png)

**Comment by cryptoBeliever** [comment]
This seems to be expected: https://github.com/nemgrouplimited/symbol-mobile-wallet/issues/30
