### ISSUE TITLE
23 instead 24 words seed

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-mobile-wallet#65]
Reported on a production app. Used Samsung 8.

User can see only 23 seed instead 24 words. How it's possible? 
Please contact me on Slack for screenshots.

**Comment by jabo38** [comment]
This might be related in someway to one of the words being used twice?

**Comment by cryptoBeliever** [comment]
@jabo38 no. All words were unique in this case.

**Comment by OlegMakarenko** [comment]
Do we still have this issue in non-opt-in wallet?  @cryptoBeliever @Peersyst
