### ISSUE TITLE
When I click the edit contact button, getting add contact

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-mobile-wallet#66]
When I click the edit contact button, getting add contact page. it should point to edit page 
![image](https://user-images.githubusercontent.com/49143210/102189924-5c2bc900-3edd-11eb-8385-cbb57c4cc32b.png)

**Comment by jabo38** [comment]
same thing for me on iOS

**Comment by Peersyst** [comment]
Marked as duplicated of #75
