### ISSUE TITLE
[iOS][Android] Don't receive Failure_RestrictionAccount_Address_Interaction_Prohibited error message

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-mobile-wallet#69]
WTR:
Given account A and B
1. Go to account A and add Incoming address restriction for account B.
2. Open mobile wallet.
3. Initiate transaction from account B to account A from mobile wallet.

Result: I don't receive Failure_RestrictionAccount_Address_Interaction_Prohibited toast message like on the web version

![image](https://user-images.githubusercontent.com/11311924/102217410-bb520380-3f06-11eb-9f4e-12944e92594b.png)

**Comment by cryptoBeliever** [comment]
@AdriaCarrera I think it's general problem that mobile wallet is not showing errors returned by API when initializing transaction. All validations are done on wallet side but not all can be checked in this way.

**Comment by cryptoBeliever** [comment]
@AdriaCarrera now the message error is presented as notification but we are still on Success view. Can we improve it somehow?

**Comment by Peersyst** [comment]
Sure. Now works as desktop wallet so let's close this one and create one enhancement for this.
