### ISSUE TITLE
scaling issues on iOS

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#71]
1. Can't see my balance on the Dashboard. 

![IMG_4602](https://user-images.githubusercontent.com/10395907/102277164-81283800-3eed-11eb-9ef1-d13727b2f012.PNG)

2. Surely that isn't how the balance is supposed to be displayed. Also, the three little dots to access the main account's details and change name are hard to click on because that is where iPhones microphone and camera at. In the screen shot, you can see them clearly, but on a real device, not so much. 

![IMG_4604](https://user-images.githubusercontent.com/10395907/102277243-98ffbc00-3eed-11eb-9b56-6f742c6daf8f.PNG)

3. Namespaces and balances blend perfectly together so it is hard to see when one starts and one ends. Also, some letters, like the "y" in Symbol, or a "j", hang outside of the boundaries of the box. 

![IMG_4601](https://user-images.githubusercontent.com/10395907/102277437-e714bf80-3eed-11eb-826b-d67d0e6e862f.PNG)

**Comment by jabo38** [comment]
a long name in the address book messes up formatting when the tx size of mosaics is large enough. 

![IMG_4612](https://user-images.githubusercontent.com/10395907/102280624-209bf980-3ef3-11eb-9c2a-e4bc186b4d78.PNG)

**Comment by Peersyst** [comment]
@jabo38 could you please tell us which device are you using? Thank you!

**Comment by cryptoBeliever** [comment]
@jabo38 @NikolaiB could you check?

**Comment by NikolaiB** [comment]
@jabo38 @cryptoBeliever fixed.
