### ISSUE TITLE
iOS paper wallet backup location not clear

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#72]
There is no paper wallet. It is not saved to documents. 
![IMG_4606](https://user-images.githubusercontent.com/10395907/102277717-4bd01a00-3eee-11eb-907b-1d971d2034b2.PNG)

**Comment by cryptoBeliever** [comment]
@NikolaiB could you please confirm on IOS?

**Comment by jabo38** [comment]
@NikoliaB can confirm, but there literally isn't a documents folder on iOS.

**Comment by Peersyst** [comment]
Paper wallet should be in the file explorer -> Symbol app

I'll change this to an improvement of the backup process in iOS

**Comment by cryptoBeliever** [comment]
@NikolaiB please verify

**Comment by NikolaiB** [comment]
fixed
