### ISSUE TITLE
App crashes when trying to scan QR code for aggregates

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#73]
I prepared the following aggregate tx on the desktop wallet. Scanned the QR with my iOS app, the app crashes. 

![image](https://user-images.githubusercontent.com/10395907/102278709-e1b87480-3eef-11eb-9dd6-fc77ebbd0192.png)

**Comment by jabo38** [comment]
At other times when I scanned it, the mobile app prepared a transaction, but only chose one of the mosaics listed. 

Here is what I see on my mobile app and the transaction went through despite the QR being for an aggregate as shown in the screenshot. 

![IMG_4608](https://user-images.githubusercontent.com/10395907/102279004-58ee0880-3ef0-11eb-8708-3767c18d8590.PNG)

here is the tx info. http://explorer-0.10.0.x-01.symboldev.network/transactions/C32836396164B8CEA0612B9194BBA0DDA97912562415A18DCBEE0320A400078E

**Comment by cryptoBeliever** [comment]
Fixed now. Wallet presenting message that sending multiple mosaics is not possible and asks user if he want send only one.
