### ISSUE TITLE
I'm about to delete all my data, not "log out"

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#74]
Usually logging out of an app implies later on you can log back in and all your data is there. This is clearly not the case. When I click "logout" I'm given a kind of bland warning that I need to have backed up my data. There should be a stern warning that proceeding will result in a loss of all funds and to get them back, a person must restore their account from a seed that has to have been backed up. 

Also, for somebody with a clumsy thumb, a little bit of miss press and all my funds are gone when I instead meant to click "Cancel".  The UX should really be a firm warning, then a checkbox that somebody has to click, then a confirm. It should not be easy to delete all your money. And for many new users, "logging out" doesn't mean full wipe of one's private keys. Technically this is a "delete all accounts and private keys" button. 

![IMG_4609](https://user-images.githubusercontent.com/10395907/102279696-7374b180-3ef1-11eb-8594-db924bfb2930.PNG)

**Comment by cryptoBeliever** [comment]
@Peersyst button name was changed, but what about translations? Would be bad if we don't update it.

**Comment by NikolaiB** [comment]
@AdriaCarrera @jabo38 @cryptoBeliever with Eng translation it fixed, but there are still a few issues with Rus translation I created another ticket for this https://github.com/nemgrouplimited/symbol-mobile-wallet/issues/117

**Comment by cryptoBeliever** [comment]
Yes. I mentioned it here https://github.com/nemgrouplimited/symbol-mobile-wallet/issues/74#issuecomment-770301139
Translation should be updated for all languages.

**Comment by cryptoBeliever** [comment]
Fixed.
