### ISSUE TITLE
Editing an Address Book contact leads to a double entry, not edit. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#75]
I made an address book entry. Went to edit it, and ended up with two entries for the same address. 

As we can see, the checksum on both accounts is "IYI".  
![IMG_4611](https://user-images.githubusercontent.com/10395907/102280975-b768b600-3ef3-11eb-8bbd-e9f8a9ee6853.PNG)

**Comment by jabo38** [comment]
also, we can see that the name for that address is too long and is cut off by the app when displaying it.

**Comment by cryptoBeliever** [comment]
Editing issue is fixed but overflows (when name is too long) are still present on address book list and details.

**Comment by cryptoBeliever** [comment]
Double entry fixed.
Problems with name length continued here https://github.com/nemgrouplimited/symbol-mobile-wallet/issues/79
