### ISSUE TITLE
When making a transactions, there is a "0" in the amount field that has to be deleted each time. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#76]
The way some apps work is that there is a "0" in the amount field. Sometimes it is partly shaded to show it isn't a "real 0" but instead a place holder. But here it is a real 0 because when I start typing, like say for instance I want to send 1 XYM so I hit "1", what I end up with is "01" and not "1".

The expected behavior is when I start to type a real number, then the 0 disappears. 

![IMG_4614](https://user-images.githubusercontent.com/10395907/102281514-aff5dc80-3ef4-11eb-93be-a7b372857021.PNG)

**Comment by jabo38** [comment]
This happens in both iOS and Android.

**Comment by cryptoBeliever** [comment]
@jabo38 fixed in latest version
