### ISSUE TITLE
App always says "Activation in progress" in the harvesting section. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#77]
I guess it goes without saying and it is being looked into, but if the server that is harvesting for the account is known, it would be nice if there was an API so that the server could be queried, "are you harvesting currently for x account". Then if so, the Status would go to green and harvesting, if not, then some kind of error message and suggestion to switch nodes.

**Comment by cryptoBeliever** [comment]
@jabo38 what node did you used to start harvesting?

**Comment by jabo38** [comment]
This was a fresh install of the app with accounts that had been activated via the desktop. I'm not really sure which node I used.

**Comment by cryptoBeliever** [comment]
Closing and leaving https://github.com/nemgrouplimited/symbol-mobile-wallet/issues/134
