### ISSUE TITLE
On Android can only back up a wallet with no passcode

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#78]
**Steps to reproduce**
try to back up a wallet when the passcode is on. Can't get past the pastcode screen after scanning with my fingerprint. 

if I remove the passcode and the wallet is unprocted, I can. 

**Expected behavior**
Should be able to back up wallets whether there is a passcode or not. 
 
**Affected Version**
Android v10, Galaxy S10

**Comment by cryptoBeliever** [comment]
@jabo38 this is backup when you already logged in settings right? This must be device specific because I'm able do it on my Samsung S20 with Android 11

**Comment by jabo38** [comment]
yes. I'm using the Symbol Beta app on a Galaxy S10

Go to settings -> 
Go to "Backup" ->
Asked for passcode via fingerprint ->
Scan fingerprint ->
Stuck on panel that has numbers to enter passcode even though my passcode has been entered via fingerprint. 

This getting stuck on this screen has happened in other places too like for sending transactions, so it is a repeat of that same issue.

**Comment by Peersyst** [comment]
This should be corrected in the last version of the app. 
Please test it and close this issue if fixed

**Comment by cryptoBeliever** [comment]
@jabo38 for me it looks correct in new version so I'm closing. But please check on your phone too. Latest version available here: http://symbol-mobile-builds.peersyst.com/
