### ISSUE TITLE
Long names in address book cause problems with scaling 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-mobile-wallet#79]
**Steps to reproduce**
Make a long name in the address book

**Current behavior**
When displaying the name the app appears wonky. 
 
**Affected Version**
Android and iOS

**Screenshots**
![image](https://user-images.githubusercontent.com/10395907/102378396-5ee4f780-3f8b-11eb-803f-2e8dbac7347f.png)

![image](https://user-images.githubusercontent.com/10395907/102378406-62787e80-3f8b-11eb-9b53-4e9689be7395.png)

I have a screenshot for iOS at https://github.com/nemgrouplimited/symbol-mobile-wallet/issues/71#issuecomment-745609456

**Comment by cryptoBeliever** [comment]
After this change:
- writing in input long name is not possible but it works strange. When I putting letter it shows and next it disappears
- I'm still able to scan Address QR from desktop wallet with very long name and it's added. After that I'm unable to edit name at all

**Comment by NikolaiB** [comment]
@jabo38 @cryptoBeliever fixed in iOS.

**Comment by cryptoBeliever** [comment]
Ok. Marked as fixed.
