### ISSUE TITLE
[iOS] The app crashes when switching between apps

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-mobile-wallet#81]
v4(6)

WTR:
1. Create two account A and B
2. Click on wallet icon and switch to account B
3. Switch to Slack
4. Switch back to the wallet

Result: the app was crashed [Video](https://www.loom.com/share/aa469d6ec5d74af9b577c3c95104ffad)

**Comment by cryptoBeliever** [comment]
@NikolaiB please verify

**Comment by NikolaiB** [comment]
fixed

**Comment by NikolaiB** [comment]
Can reproduce with 4(12) build.
