### ISSUE TITLE
[Android] Getting `Failed to send transaction. Recipient address has not a public key` error with encrypted message

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-mobile-wallet#83]
WTR:
1. Create new account
2. Initiate transaction with encrypted message

Result: transaction can not bee initiated with encrypted message for a new account. [Video](https://www.loom.com/share/1bab5f527cf8414ba05a7a9cfced5468)

![image](https://user-images.githubusercontent.com/11311924/102975365-282e5480-452a-11eb-9560-7f216355f3d8.png)

**Comment by Peersyst** [comment]
Symbol doesn't allow to send transactions with encrypted message to virgin accounts (they haven't made any transaction yet). As the recipient doesn't have a public key yet
