### ISSUE TITLE
new mobile phone can't login.

### ISSUE THREAD

**Issue by wonnicn** [nemgrouplimited/symbol-mobile-wallet#85]
new mobile phone can't login. After scanning QR code and entering the password, the input method does not disappear and can't login.

**Comment by wonnicn** [comment]
![image](https://user-images.githubusercontent.com/14865901/104080208-10650900-526a-11eb-9999-b98358302c6e.jpeg)

The next key not work.

**Comment by cryptoBeliever** [comment]
@Peersyst it's IPhone 12.

**Comment by wonnicn** [comment]
It's iPhone8 plus @Peersyst
