### ISSUE TITLE
Pincode text big and not centered

### ISSUE THREAD

**Issue by Peersyst** [nemgrouplimited/symbol-mobile-wallet#87]
**Steps to reproduce**
- Change language to japanese
- Go to Pincode

**Current behavior**
![japanese_long_text](https://user-images.githubusercontent.com/54996852/104159538-cb6adf00-53ef-11eb-9027-0715bd0c1471.jpg)

**Expected behavior**
Should be smaller text, or separated in two lines

**Comment by cryptoBeliever** [comment]
Fixed.
