### ISSUE TITLE
iPad does not display the app full screen

### ISSUE THREAD

**Issue by Peersyst** [nemgrouplimited/symbol-mobile-wallet#89]
![ipad](https://user-images.githubusercontent.com/54996852/104160996-58169c80-53f2-11eb-8588-e351abf69635.jpg)

**Comment by cryptoBeliever** [comment]
@NikolaiB have you iPad to verify?

**Comment by cryptoBeliever** [comment]
@Peersyst I don't have IPad to check. So if you confirmed that it's fixed please close.

**Comment by surekabpm** [comment]
Tested, it displays the full screen
![ipad_screen](https://user-images.githubusercontent.com/49143210/110479690-b10d6300-810b-11eb-956f-8ef581c3ca91.JPG)

**Comment by surekabpm** [comment]
This issue can be cosed
