### ISSUE TITLE
Proplem with Run Android ( android studio)

### ISSUE THREAD

**Issue by hao1234nguyen** [nemgrouplimited/symbol-mobile-wallet#93]
I have a proplem when i run 
Here is proplem (link: https://drive.google.com/file/d/1EyjqmBtbm9UxxXGMLw8cOp-ijT3Q-T7Z/view?usp=sharing)
I have followed the steps in the readme file
i use window
$ git clone <url/to/this/project>
$ cd <path/to/this/project>
$ cp env/default.json.example env/default.json # now add your network configuration
$ yarn install # or npm install
Open a new tab and

$ react-native start # --resetCache (for a clean build)
To run,

$ react-native run-android --variant=devDebug # or react-native run-ios (if you are on macOS)

**Comment by Peersyst** [comment]
Please check that your bundle location is correct:
https://stackoverflow.com/questions/42064283/could-not-connect-to-react-native-development-server-on-android
